name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at 6:00 PM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: yashvisharma1204
          outputs: |
            dist/snake.svg

      - name: Upload Snake Animation as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-graph
          path: dist/snake.svg

      - name: Commit & Push Snake Animation to Profile Repo
        run: |
          mkdir -p assets
          cp dist/snake.svg assets/snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/snake.svg
          git commit -m "chore: update contribution snake" || echo "No changes"
          git push
